### ISSUE TITLE
wherer are the mappings

### ISSUE THREAD

**Issue by ashidooo** [Lunar-Mapping-Project/mappings#1]
ware are the mapings desencies

**Comment by Nopock** [comment]
fr

**Comment by Noxiuam** [comment]
up your ass

**Comment by Moose1301** [comment]
lunar.mappings.local/download for mappings!!!!
!!

**Comment by SIMULATAN** [comment]
omg it work no scam!!!!
thanks!!
!!

**Comment by Decencies** [comment]
Refer to https://github.com/Lunar-Mapping-Project/mappings#where-are-the-mappings.
